name: lectorem
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  flutter_spinkit: ^4.1.2
  webview_flutter: ^0.3.21
  json_serializable: ^3.3.0
  provider: ^4.0.5+1
  shared_preferences: ^0.5.7
  intl: ^0.16.1
  flutter_html: ^0.11.1
  url_launcher: ^5.4.5
  cached_network_image: ^2.2.0+1
  font_awesome_flutter: ^8.8.1
  animated_text_kit: ^2.0.1
  google_fonts: ^1.0.0
  html: ^0.14.0+3
  animations: ^1.0.0+5
  connectivity: ^0.4.8+5
  shimmer: ^1.1.1
  flutter_platform_widgets: ^0.40.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0


flutter:
  uses-material-design: true

  assets:
    - assets/